# Generated by Django 5.1.7 on 2025-03-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='description',
            field=models.CharField(max_length=560),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
