# Generated by Django 5.1.7 on 2025-04-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_movement_description_movement_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('description', models.CharField(max_length=560)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
