# Generated by Django 5.1.7 on 2025-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_movementtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='movement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
